version: 2

project_name: toba

before:
  hooks:
    - go test ./...

builds:
  - id: toba-linux
    main: ./
    binary: toba
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/gotcha190/toba/internal/cli.releaseVersion={{ .Version }}

  - id: toba-darwin
    main: ./
    binary: toba
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/gotcha190/toba/internal/cli.releaseVersion={{ .Version }}

  - id: toba-windows
    main: ./
    binary: toba
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/gotcha190/toba/internal/cli.releaseVersion={{ .Version }}

archives:
  - id: linux-archives
    ids:
      - toba-linux
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'

  - id: darwin-archives
    ids:
      - toba-darwin
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'

  - id: windows-archives
    ids:
      - toba-windows
    formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge "

release:
  github:
    owner: Gotcha190
    name: ToBA

homebrew_casks:
  - name: toba
    ids:
      - darwin-archives
    binaries:
      - toba
    directory: Casks
    homepage: "https://github.com/Gotcha190/ToBA"
    description: "CLI for creating local WordPress environments with Lando"
    commit_msg_template: "Bump toba cask to {{ .Tag }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toba"]
          end
    repository:
      owner: Gotcha190
      name: homebrew-toba
      branch: main
    commit_author:
      name: gotcha190
      email: gotcha190@users.noreply.github.com
