#!/usr/bin/env bash

set -euo pipefail

tag="${1:?usage: publish-homebrew-formula.sh <tag> <tap-dir> [dist-dir]}"
tap_dir="${2:?usage: publish-homebrew-formula.sh <tag> <tap-dir> [dist-dir]}"
dist_dir="${3:-dist}"

version="${tag#v}"
project="toba"
release_base_url="https://github.com/Gotcha190/ToBA/releases/download/${tag}"
formula_dir="${tap_dir}/Formula"
formula_path="${formula_dir}/toba.rb"
cask_path="${tap_dir}/Casks/toba.rb"

sha_file() {
	local path="$1"
	sha256sum "$path" | awk '{print $1}'
}

darwin_x86_64_archive="${project}_${version}_darwin_x86_64.tar.gz"
darwin_arm64_archive="${project}_${version}_darwin_arm64.tar.gz"
linux_x86_64_archive="${project}_${version}_linux_x86_64.tar.gz"
linux_arm64_archive="${project}_${version}_linux_arm64.tar.gz"

darwin_x86_64_sha="$(sha_file "${dist_dir}/${darwin_x86_64_archive}")"
darwin_arm64_sha="$(sha_file "${dist_dir}/${darwin_arm64_archive}")"
linux_x86_64_sha="$(sha_file "${dist_dir}/${linux_x86_64_archive}")"
linux_arm64_sha="$(sha_file "${dist_dir}/${linux_arm64_archive}")"

mkdir -p "${formula_dir}"

cat > "${formula_path}" <<EOF
# This file was generated by the ToBA release workflow. DO NOT EDIT.
class Toba < Formula
  desc "CLI for creating local WordPress environments with Lando"
  homepage "https://github.com/Gotcha190/ToBA"
  version "${version}"
  license "MIT"

  on_macos do
    on_intel do
      url "${release_base_url}/${darwin_x86_64_archive}"
      sha256 "${darwin_x86_64_sha}"
    end
    on_arm do
      url "${release_base_url}/${darwin_arm64_archive}"
      sha256 "${darwin_arm64_sha}"
    end
  end

  on_linux do
    on_intel do
      url "${release_base_url}/${linux_x86_64_archive}"
      sha256 "${linux_x86_64_sha}"
    end
    on_arm do
      url "${release_base_url}/${linux_arm64_archive}"
      sha256 "${linux_arm64_sha}"
    end
  end

  def install
    bin.install "toba"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/toba version")
  end
end
EOF

if [ -f "${cask_path}" ]; then
	rm -f "${cask_path}"
fi

git -C "${tap_dir}" config user.name "gotcha190"
git -C "${tap_dir}" config user.email "gotcha190@users.noreply.github.com"
git -C "${tap_dir}" add -A -- Formula/toba.rb Casks/toba.rb
if git -C "${tap_dir}" diff --cached --quiet; then
	exit 0
fi

git -C "${tap_dir}" commit -m "Bump toba formula to ${tag}"
git -C "${tap_dir}" push origin main
